params {
    //Global pipeline run options
    //run_mode options: pre_isoquant, full
    run_mode="pre_quant" 
    //new_test_value
    number_of_chunks=10
    //Input samples. Comma-separated file with path and sample_id. No header
    //used to look for data and resources. Should end with a "/"
    nf_basedir = "/nfs/team152/sk38/wtsi-pbsc/" 
    subset_regions_bed = "/lustre/scratch124/humgen/projects_v2/isoibd/resources/coding_regions_GRCh38__chr.bed"
    //input_samples_path = "/lustre/scratch124/humgen/projects_v2/isoibd/metadata/input_freeze01_20250807.csv"
    //input_samples_path = "/lustre/scratch124/humgen/projects_v2/isoibd/metadata/input_freeze01_20250820.csv"
    //input_samples_path = "/lustre/scratch126/humgen/teams_v2/hgi/vo3/isoseq_test/input_freeze01_20250820_one_sample.csv"
    //input_samples_path = "/lustre/scratch124/humgen/projects_v2/isoibd/metadata/input_freeze02_20250807.csv"
    input_samples_path = "/lustre/scratch124/humgen/projects_v2/isoibd/sk38/input_test.csv"
    dedup_batch_size = 5000000
    //exclude_samples = "/lustre/scratch127/humgen/teams_v2/hgi/vo3/isoseq_test/excluded_samples.csv"

    //Skera primers used by Skera to deconcatenate Kinnex reads
    skera_primers = "/lustre/scratch125/humgen/resources_v2/PacBio_reference/MAS-Seq_Adapter_v1/mas16_primers.fasta"
    //10X primers
    tenx_primers = "/lustre/scratch125/humgen/resources_v2/PacBio_reference/REF-10x_primers/10x_3kit_primers.fasta"
    //Directory to output results
    results_output = "/lustre/scratch124/humgen/projects_v2/isoibd/sk38/lori_out"
    //Minimum polyA length to refine reads
    min_polya_length = 20
    //10X cell barcode whitelist
    threeprime_whitelist = "/lustre/scratch125/humgen/resources_v2/PacBio_reference/cell_barcodes_whitelist/3M-february-2018-REVERSE-COMPLEMENTED.txt"
    //Genome FASTA files
    genome_fasta_f = "/lustre/scratch125/humgen/resources_v2/PacBio_reference/refdata-cellranger-arc-GRCh38-2020-A/refdata-cellranger-arc-GRCh38-2020-A.genome.fa"
    //Barcode correction strategy (used by isoseq correct; percentile or knee)
    barcode_correction_method = "percentile"
    barcode_correction_percentile = "98"
    dedup_real_cells_only = "TRUE"
    //Run gtcheck or not and the file with ref GT VCFs
    run_gtcheck = "TRUE"
    tsv_donor_panel_vcfs = "/lustre/scratch124/humgen/projects_v2/isoibd/resources/genotyping/donor_panels_vcf_test_new.tsv"
    ZSCORE_THRESH= 8
    ZSCORE_DIST_THRESH= 8
    run_barcode_check = "TRUE"
    ref_barcode_list="/lustre/scratch124/humgen/projects_v2/isoibd/freeze02/output/deconvolution/short_read/barcode_map.tsv"
    min_common_barcodes_percent=70
    min_n_common_barcodes=100
    
    ///// SQANTI3 files //////
    //SQANTI3 software path
    sqanti3_path = "/nfs/team152/sk38/tools/SQANTI3-6.0/"
    //CAGE peaks 
    cage_peak_f = "/lustre/scratch124/humgen/projects_v2/isoibd/sk38/references/refTSS_v4.1_human_coordinate_no_header.hg38.bed"
    //PolyA sites in the human genome (used by SQANTI3)
    polya_sites = "/lustre/scratch124/humgen/projects_v2/isoibd/sk38/references/atlas.clusters.2.0.GRCh38.96.bed"
    //PolyA motifs
    polya_f = "/lustre/scratch124/humgen/projects_v2/isoibd/sk38/references/mouse_and_human.polyA_motif.txt"
    //SQANTI3 rules filter JSON
    sqanti_filter_json = "/nfs/team152/sk38/wtsi-pbsc/conf/sqanti_filter.json"


    ///// IsoQuant files //////
    chunks = 16
    isoquant_exclusion_regions_bed = "/nfs/team152/sk38/wtsi-pbsc/data/vdj_genes.bed"
    //GTF file (used by isoquant)
    gtf_f = "/lustre/scratch124/humgen/projects_v2/isoibd/sk38/references/gencode.v49.annotation.gtf"
    custom_config_version      = 'master'
    custom_config_base         = "https://raw.githubusercontent.com/nf-core/configs/${params.custom_config_version}"
    workdir = './work'
}
